# Practice Session 1.2


In [1]:
rm (list = ls())

### 1. Create a vector 'x' having values (1,2,3,4 and 5) and multiple each element by 2.


In [2]:
x <- c(1,2,3,4,5)
cat("\n Mutplied by 2, the value of \'x\' (",x,") becomes ==", x * 2)


 Mutplied by 2, the value of 'x' ( 1 2 3 4 5 ) becomes == 2 4 6 8 10

### 2. Create a vector named 'vowels' containing all the vowels in English language

In [3]:
vowels <- letters[c(1,5,9,15,21)]
cat("\nThe vowels in English language are ==> ", vowels)


The vowels in English language are ==>  a e i o u

### 3. Create a vector 'rep.num' of numbers 0 and 1, 5 times each


In [5]:
cat ("\n Repeat 0 and 1, 5 times each can be done either as == ", rep(c(0,1), each = 5)," \n OR as == ", rep(c(0,1),5))


 Repeat 0 and 1, 5 times each can be done either as ==  0 0 0 0 0 1 1 1 1 1  
 OR as ==  0 1 0 1 0 1 0 1 0 1

### 4. Generate a sequence 'seq.1' from 1 to 25 in steps of 2

In [9]:
seq.1 <- seq(1,25,2)
cat("\n The sequence generated is ==> ", seq.1, "\n")
cat("\n The number of elements in the sequence", length(seq.1))
cat("\n The element at 7th position ", seq.1[7])
cat("\n List of elements from the sequence, expect the elements from the  position 3, 6, and 9 ==> ",seq.1[-c(3,6,9)])


 The sequence generated is ==>  1 3 5 7 9 11 13 15 17 19 21 23 25 

 The number of elements in the sequence 13
 The element at 7th position  13
 List of elements from the sequence, expect the elements from the  position 3, 6, and 9 ==>  1 3 7 9 13 15 19 21 23 25


### 5. Generate a sequencce 'seq.2' from -3 to 3 with 10 evenly distributed elements and print all the elements less than 1.

In [11]:
seq.2 <- seq(-3,3,  length.out = 10)
cat("\n Sequence from -3 to 3 with 10 evenly distributed elements ==> \n", seq.2, "\n\n")
cat("\n List of elements which are less than 1 ==> \n", seq.2[seq.2 <1])


 Sequence from -3 to 3 with 10 evenly distributed elements ==> 
 -3 -2.333333 -1.666667 -1 -0.3333333 0.3333333 1 1.666667 2.333333 3 


 List of elements which are less than 1 ==> 
 -3 -2.333333 -1.666667 -1 -0.3333333 0.3333333

### 6. Create a matrix 'Mat.1' of 2 rows and 3 columns having elements (2,1,3,6,4,5) and find the transpose

In [12]:
mat.1 <- matrix(c(2,1,3,6,4,5), nrow = 2, byrow = T)
mat.1
print("The transpose (t()) of matrix  is ==> ")
t(mat.1)

[,1] [,2] [,3]
[1,]    2    1    3
[2,]    6    4    5

[1] "The transpose (t()) of matrix  is ==> "


[,1] [,2]
[1,]    2    6
[2,]    1    4
[3,]    3    5

### 7. Create a 4x4 diagonal matrix having elements 1, 2, 3 and 4 and another 4x3 matrix having elements from 1 to 12 and then  perform multiplication operations on both these matrices


In [13]:
m1 <- diag(c(1,2,3,4), nrow=4 , ncol=4)
print("First Matrix")
m1
m2 <- matrix(seq(1,12), nrow=4)
print("Second Matrix")
m2
matMulti <- m1 %*% m2
print("...Now performing Matrix multiplication on the above two matrices to get the below results")
matMulti

[1] "First Matrix"


[,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    2    0    0
[3,]    0    0    3    0
[4,]    0    0    0    4

[1] "Second Matrix"


[,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

[1] "...Now performing Matrix multiplication on the above two matrices to get the below results"


[,1] [,2] [,3]
[1,]    1    5    9
[2,]    4   12   20
[3,]    9   21   33
[4,]   16   32   48

### 8. Create an array with dimensions 2 x 3 x 4 and elements 1-24.

#### Not sure why the 3d array is not getting printed the way it does on R-Console/R-Studio, will try searching for a solution.

In [14]:
arr3D <- array(1:24,dim = c(2,3,4), dimnames = list(c("row1", "row2"),
               c("col.1","col.2","col.3"),
               c("level1","level2","level3","level4")))
arr3D

, , level1

     col.1 col.2 col.3
row1     1     3     5
row2     2     4     6

, , level2

     col.1 col.2 col.3
row1     7     9    11
row2     8    10    12

, , level3

     col.1 col.2 col.3
row1    13    15    17
row2    14    16    18

, , level4

     col.1 col.2 col.3
row1    19    21    23
row2    20    22    24